[package]
name = "galileo-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
galileo-core.workspace = true
clickhouse.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true
async-trait.workspace = true
futures.workspace = true
indexmap.workspace = true

[dev-dependencies]
tokio.workspace = true
